[package]
name = "quartz_plugins"
version = "0.1.0"
authors = ["maddymakesgames", "Cassy343"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libloading = "0.6.2"
log = "0.4.11"
log4rs = "0.12.0"