[package]
name = "quartz_macros"
version = "0.1.0"
authors = ["maddymakesgames", "Cassy343"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.31"
quote = "1.0.7"
proc-macro2 = "1.0.18"