[package]
name = "quartz_util"
version = "0.1.0"
authors = ["Cassy343", "maddymakesgames"]
edition = "2021"

[dependencies]
anyhow = "1.0"
chrono = "0.4"
flate2 = "1.0"
linefeed = "0.6"
log = "0.4"
log4rs = "1.1"
rand = "0.8"
serde = "1.0.126"

[target.'cfg(unix)'.dependencies]
termion = "1.5"