[package]
name = "quartz_macros"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quartz_macros_impl = { path = '../macros_impl' }
syn = { version = "1.0", features = ["full"] }
