[package]
name = "quartz"
version = "0.1.0"
authors = ["maddymakesgames", "Cassy343"]
edition = "2018"

[[bin]]
name = "quartz_launcher"
path = "src/main.rs"

[lib]
name = "quartz"
path = "src/lib.rs"

[dependencies]
# Internal dependencies
chat = { path = "../chat" }
quartz_plugins = { path = "../quartz_plugins" }
quartz_macros = { path = "../quartz_macros" }
util = { path = "../util" }

# External dependencies
array-init = "0.1.1"
byteorder = "1.3.4"
chrono = "0.4.13"
enum_dispatch = "0.3.1"
flate2 = "1.0.16"
futures-lite = "1.11.2"
hex = "0.4.2"
itertools = "0.9.0"
lazy_static = "1.4.0"
linefeed = "0.6.0"
log = "0.4.11"
log4rs = "0.12.0"
num-traits = "0.2.14"
once_cell = "1.4.0"
openssl = "0.10.30"
phf = { version = "0.8.0", features = ["macros"] }
quartz_nbt = "0.1.0"
rand = "0.7.3"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = "1.4.0"
smol = "1.2.4"
tinyvec = "1.0.0"
ureq = { version = "1.3.0", features = ["json"] }
uuid = { version = "0.8.1", features = ["serde", "v4"] }

[build-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[target.'cfg(unix)'.dependencies]
termion = "1.5.5"